# Ruff configuration for ros_to_markdown
# See https://docs.astral.sh/ruff/settings/

# Target Python versions
target-version = "py38"  # Lowest supported version (for ROS Noetic)

# Line length to match project standards
line-length = 100

# Exclude common directories
exclude = [
    ".git",
    ".mypy_cache",
    ".ruff_cache",
    ".venv",
    "__pycache__",
    "build",
    "dist",
    "tests_old",
    "src/ros_to_markdown_old",
]

[lint]
# Enable all recommended rules
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "N",   # pep8-naming
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "DTZ", # flake8-datetimez
    "RET", # flake8-return
    "SIM", # flake8-simplify
]

# Ignore certain rules
# ignore = [
#     "D203",  # one-blank-line-before-class (conflicts with D211)
#     "D212",  # multi-line-summary-first-line (conflicts with D213)
#     "D107",  # missing docstring in __init__
# ]

# Per-file ignores
[lint.per-file-ignores]
"tests/*" = [
    "S101",  # Use of assert
    "E501",  # Line too long
]
"scripts/**/*" = [
    "T201",  # Allow print statements in scripts
]
"src/ros_to_markdown/ros2/workspace.py" = [
    "E741",  # Ambiguous variable names specifically for this file
]
"examples/**/*" = [
    "T201",  # Allow print statements in examples
]

[lint.pydocstyle]
convention = "google"      # Use Google-style docstrings

[lint.isort]
combine-as-imports = true
force-sort-within-sections = true
known-first-party = ["ros_to_markdown"]
known-third-party = ["rclpy", "rospy"]
section-order = ["future", "standard-library", "first-party", "third-party", "local-folder"] 
