x-labels: &common-labels
  com.ros-to-markdown: "true"
  com.ros-to-markdown.project: "ros_to_markdown"
  com.ros-to-markdown.maintainer: "Rob Royce"

services:
  ros1:
    build:
      context: .
      dockerfile: docker/Dockerfile.ros1
    volumes:
      - .:/workspace:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority:ro
    environment:
      - ROS_DISTRO=noetic
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NO_AT_BRIDGE=1
    network_mode: host
    privileged: true
    extra_hosts:
      - ${DOCKER_EXTRA_HOSTS:-host.docker.internal:host-gateway}
    labels:
      <<: *common-labels
      com.ros-to-markdown.distro: "noetic"
      com.ros-to-markdown.type: "base"
    working_dir: /workspace
    entrypoint: ["/ros1-entrypoint.sh"]

  ros1-dev:
    extends: ros1
    command: launch-ros1-test-env.sh
    labels:
      <<: *common-labels
      com.ros-to-markdown.distro: "noetic"
      com.ros-to-markdown.type: "dev"

  # ROS2 Humble services
  ros2-humble:
    build:
      context: .
      dockerfile: docker/Dockerfile.ros2-humble
    volumes:
      - .:/workspace:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - ROS_DISTRO=humble
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.Xauthority
      - DEBIAN_FRONTEND=noninteractive
      - INCLUDE_JOYSTICK=0
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - RCUTILS_LOGGING_BUFFERED_STREAM=1
      - RCUTILS_LOGGING_USE_STDOUT=1
      - RCUTILS_COLORIZED_OUTPUT=1
      - PYTHONPATH=/workspace/src:/opt/ros/humble/lib/python3.10/site-packages
    network_mode: host
    privileged: true
    labels:
      <<: *common-labels
      com.ros-to-markdown.distro: "humble"
      com.ros-to-markdown.type: "base"
    working_dir: /workspace
    entrypoint: ["/ros2-entrypoint.sh"]

  ros2-humble-dev:
    extends: ros2-humble
    command: launch-ros2-test-env.sh

  # ROS2 Iron services
  ros2-iron:
    build:
      context: .
      dockerfile: docker/Dockerfile.ros2-iron
    volumes:
      - .:/workspace:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - ROS_DISTRO=iron
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.Xauthority
      - DEBIAN_FRONTEND=noninteractive
      - INCLUDE_JOYSTICK=0
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - RCUTILS_LOGGING_BUFFERED_STREAM=1
      - RCUTILS_LOGGING_USE_STDOUT=1
      - RCUTILS_COLORIZED_OUTPUT=1
      - PYTHONPATH=/workspace/src:/opt/ros/iron/lib/python3.10/site-packages
    network_mode: host
    privileged: true
    labels:
      <<: *common-labels
      com.ros-to-markdown.distro: "iron"
      com.ros-to-markdown.type: "base"
    working_dir: /workspace
    entrypoint: ["/ros2-entrypoint.sh"]

  ros2-iron-dev:
    extends: ros2-iron
    command: launch-ros2-test-env.sh

  # ROS2 Jazzy services
  ros2-jazzy:
    build:
      context: .
      dockerfile: docker/Dockerfile.ros2-jazzy
    volumes:
      - .:/workspace:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - ROS_DISTRO=jazzy
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.Xauthority
      - DEBIAN_FRONTEND=noninteractive
      - INCLUDE_JOYSTICK=0
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - RCUTILS_LOGGING_BUFFERED_STREAM=1
      - RCUTILS_LOGGING_USE_STDOUT=1
      - RCUTILS_COLORIZED_OUTPUT=1
      - PYTHONPATH=/workspace/src:/opt/ros/jazzy/lib/python3.12/site-packages
    network_mode: host
    privileged: true
    labels:
      <<: *common-labels
      com.ros-to-markdown.distro: "jazzy"
      com.ros-to-markdown.type: "base"
    working_dir: /workspace
    entrypoint: ["/ros2-jazzy-entrypoint.sh"]

  ros2-jazzy-dev:
    extends: ros2-jazzy
    command: launch-ros2-test-env.sh
    environment:
      - VIRTUAL_ENV=/home/ros/.venv
      - PATH=/home/ros/.venv/bin:$PATH

  # Test environments
  test-ros1:
    extends: ros1
    command: pytest tests/

  test-ros2-humble:
    extends: ros2-humble
    command: pytest tests/

  test-ros2-iron:
    extends: ros2-iron
    command: pytest tests/
  test-ros2-jazzy:
    extends: ros2-jazzy
    command: pytest tests/

